- hosts: localhost
  vars:
    is_linux: "{{ lookup('pipe', 'uname') == 'Linux' }}"
    vimrcs: ['.vimrc', '.ideavimrc']
    git_configs:
      - name: user.name
        value: Andrei Kazakov
      - name: core.editor
        value: vim
      - name: color.ui
        value: auto
      - name: alias.ll
        value: log --abbrev-commit --abbrev=6 --format="%h %Cblue%aN%Cgreen%d%Creset %s" --graph --decorate=short
      - name: alias.d
        value: diff --minimal --word-diff=color --word-diff-regex=\"([0-9@A-Za-z]+|[^0-9@A-Za-z()]+|[()])\"
      - name: alias.sho
        value: show --minimal --word-diff=color --word-diff-regex=\"([0-9@A-Za-z]+|[^0-9@A-Za-z()]+|[()])\"
      - name: core.excludesfile
        value: ~/.dot/.gitignore
    git_configs_mac:
      - name: core.pager
        value: '`brew --prefix git`/share/git-core/contrib/diff-highlight/diff-highlight | less -r'
      - name: interactive.diffFilter
        value: '`brew --prefix git`/share/git-core/contrib/diff-highlight/diff-highlight'
    common_packages:
      - docker
      - fzf
      - git
      - go
      - htop
      - httpie
      - jq
      - make
      - neovim
      - nvm
      - ripgrep
      - rust-analyzer
      - tig
      - tmux
      - tree
      - unzip
      - fish
    brew_packages:
      - autojump
      - bash
      - make
      - python3
    cask_packages:
      - alacritty
      - homebrew/cask-fonts/font-ubuntu-mono-nerd-font
    pacman_packages:
      - alacritty
      - python
      - gvim

  tasks:
    - name: Copy common configs
      copy:
        src: .dot/
        dest: ~/.dot/

    - name: Create a ~/bin directory if it does not exist
      file:
        path: ~/bin
        state: directory
        mode: '0755'

    - name: Install all the packages (Pacman)
      become: yes
      package:
        name: '{{ item }}'
        state: latest
      with_items: '{{ common_packages + pacman_packages }}'
      when: is_linux

    - name: Install all the packages (Homebrew)
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items: '{{ common_packages + brew_packages }}'
      when: not is_linux

    - name: Install all the packages (Cask)
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      with_items: '{{ cask_packages }}'
      when: not is_linux

    - name: Install cargo
      shell: curl https://sh.rustup.rs -sSfy | bash -s -- -y

    - name: Set up git configs
      git_config:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        scope: global
      with_items: '{{ git_configs }}'

    - name: Set up git configs (Mac OS)
      git_config:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        scope: global
      with_items: '{{ git_configs_mac }}'
      when: not is_linux

    - name: Create vim files
      copy:
        content: ""
        dest: '~/{{ item }}'
        force: no
      with_items: '{{ vimrcs }}'

    - name: Source common vim configs
      lineinfile:
        path: '~/{{ item }}'
        line: source ~/.dot/.vimrc
      with_items: '{{ vimrcs }}'

    - name: Create alacritty config
      copy:
        src: './.dot/.alacritty.yml'
        dest: '~/.alacritty.yml'
        force: no

    - name: Create tmux config
      copy:
        content: "source-file ~/.dot/.tmux.conf"
        dest: '~/.tmux.conf'
        force: no

    - name: Source common fish configs
      lineinfile:
        path: ~/.config/fish/config.fish
        line: source ~/.dot/config.fish

    - name: Use fish as a default shell
      become: true
      shell: chsh -s /bin/fish

    - name: Install Lunar Vim
      shell: LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)

    - name: Copy Lunar Vim config
      copy:
        src: './.dot/config.lua'
        dest: '~/.config/lvim/config.lua'
        force: no

